/**:
    ros__parameters:
        feature_extract_enable: false
        save_map_enable: true
        point_filter_num: 3
        max_iteration: 5
        filter_size_surf: 0.15
        filter_size_map: 0.3
        cube_side_length: 400.0      # 减小局部地图，节省内存
        runtime_pos_log_enable: false
        map_file_path: "/home/unitree/Go2_Nav_ws/src/Go2_SLAM/FAST_LIO_ROS2/PCD/map.pcd"

        common:
            lid_topic:  "/livox/lidar"
            imu_topic:  "/livox/imu"
            time_sync_en: true
            time_offset_lidar_to_imu: 0.03616488

        preprocess:
            lidar_type: 1            # MID360 Livox CustomMsg格式
            scan_line: 4             # MID360 必须是 4
            blind: 0.2               # 降低盲区，解决 No Effective Points
            timestamp_unit: 1        # 1 = us，Livox CustomMsg 时间戳单位
            scan_rate: 10

        mapping:
            acc_cov: 0.12
            gyr_cov: 0.2
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            fov_degree: 360.0
            det_range: 100.0
            extrinsic_est_en: false
            extrinsic_T: [ 0.163, 0.0, 0.140]
            extrinsic_R: [ 0.9743701, 0., 0.2249511,
                           0., 1., 0.,
                          -0.2249511, 0., 0.9743701]

        publish:
            map_frame: camera_init
            odom_frame: camera_init
            body_frame: base_link
            path_en: true
            effect_map_en: false
            map_en: true
            scan_publish_en: true
            dense_publish_en: false
            scan_bodyframe_pub_en: true

        pcd_save:
            pcd_save_en: true
            interval: -1             # 禁止运行中自动写硬盘
